---
version: 2.1
orbs:
  kitchen: sous-chefs/kitchen@2
workflows:
  danger:
    jobs:
      # Lint and Unit Test
      - kitchen/yamllint:
          name: lint-yaml
      - kitchen/mdlint:
          name: lint-markdown
      - kitchen/danger:
          name: danger
          context: Danger
