---
version: 2.1
orbs:
  kitchen: sous-chefs/kitchen@2.1.1
workflows:
  danger:
    jobs:
      # Lint and Unit Test
      - kitchen/yamllint:
          name: lint-yaml
      - kitchen/danger:
          name: danger
      - kitchen/dokken:
          name: dokken
