---
version: 2.1
orbs:
  kitchen: sous-chefs/kitchen@2.1.1
workflows:
  test:
    jobs:
      # Lint and Unit Test
      - kitchen/yamllint:
          name: lint-yaml
      - kitchen/dokken-single:
          name: dokken-single
          suite: default
