---
version: 2.1
orbs:
  kitchen: sous-chefs/kitchen@2.1.1
jobs:
  cookstyle:
    docker:
      - image: chef/chef:current
    steps:
      - checkout
      - run: chef env --chef-license accept-silent
      - run: chef exec cookstyle .
  foodcritic:
    docker:
      - image: chef/chef:current
    steps:
      - checkout
      - run: chef env --chef-license accept-silent
      - run: chef exec foodcritic .

workflows:
  test:
    jobs:
      # Lint and Unit Test
      - kitchen/yamllint:
          name: lint-yaml
      - kitchen/dokken-single:
          name: dokken-single
          suite: default
      - cookstyle
      - foodcritic
